In [1]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

# Задание 4

In [9]:
import numpy as np
from numpy import linalg

In [ ]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
n = np.arange(0, 10)
np.flip(n, axis=0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
n = np.arange(2, 11)
n = np.flip(n, axis=0)
n = n.reshape(3, 3)
ns = n.diagonal().sum()
print(f"{n}/n{ns}")

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]/n18


In [16]:
# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) # коэф. в левой части уравнения
b = np.array([4, 12, -3])
sol = linalg.solve(a,b) # решение
check = np.allclose(np.dot(a, linalg.solve(a, b)), b)
print(f'{sol} \n {check}')

[ 0.46666667  3.84444444 -5.55555556] 
 True


In [30]:
# Задание 4
# Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.
# На сайт заходит очередной посетитель, о покупках которого известно следующее:
# # next_user_stats = np.array([0, 1, 2, 0, 0, 0])
# Найдите индекс самого похожего пользователя max_index.
# Нумерацию индексов следует начинать с 0.

import numpy as np
from numpy import linalg
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
pcos = 0
a = 0
for i, c in enumerate(users_stats):
    cos = np.dot(next_user_stats, c)/(np.linalg.norm(next_user_stats)*np.linalg.norm(c))
    if cos > pcos:
        pcos = cos
        a = i
    # print(i, c, cos, pcos, a) # для отслеживания при разработке
a

7

In [31]:
# Тренировка
a = np.array([0, 0, 0, 0, 0, 5])
b = np.array([0, 1, 2, 0, 0, 0])
np.dot(a, b)/(np.linalg.norm(a)*np.linalg.norm(b))

0.0