In [ ]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

# Задание 4

In [2]:
import numpy as np

In [20]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
n = np.arange(0, 10)
np.flip(n, axis=0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
n = np.arange(2, 11)
n = np.flip(n, axis=0)
n = n.reshape(3, 3)
ns = n.diagonal().sum()
print(f"{n}/n{ns}")

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]/n18
